### PR TITLE
actools issue #116 add Kosovo to driver nationality list

### PR DESCRIPTION
**Pull request by barf**
actools issue #116
https://github.com/gro-ove/actools/issues/116

adds Kosovo flags and country to the JSON lists

### CODE REVIEW

**Comment by JoshButler** [comment]
Hey @gro-ove 
Just wanted to give this PR a little bump ⬆️. Kosovo is ready to join the race, and we’re eager to see the flag flying high! Appreciate your attention to this—let’s get this over the finish line!

Thanks for all your hard work!

**Comment by barf** [comment]
The stagnation here makes me wonder if CM needs forking... gro-ove's work is appreciated here too, but if he can't participate in open source development maybe it's time for the community to take leadership

**Comment by gro-ove** [comment]
Very sorry for the delay, got a bit stuck reworking content autoupdates backend, so it could act as CM Workshop in the near future. Thank you for the contribution!

**Comment by barf** [comment]
You're a legend gro-ove! Kia ora!

**Pull request merged**
